### ISSUE TITLE
Behavior of EV calculations

### ISSUE THREAD

**Issue by soladev** [momibun926/redmine_issue_evm#199]
I have a small question about how EV calculations are done. Let me explain what I observed :

- On **day 1**, I've completed an issue "1" (Estimated time : 3h) and started working on an issue "2" at 80% (Estimated time : 3h). So as expected, the EV value on day 1 is **5.4**.
- On **day 2**, I've completed issue "2" completely. So EV value of day 2 is 6, but on graph, EV value of day 1 dropped to **3**. (Side-note : If I set the status date back to day 1, I still have an EV value on day 1 to 5.4)

I wonder if it's an expected behavior (maybe it's no possible to get progress rate modifications on each day) and if it could be fixed. 

If not, I still have the workaround to set status date and get values every day to report them on an external spreadsheet, but it could be more convenient to have the correct EV values right from the start

**Comment by momibun926** [comment]
hi,
Thank you for reporting.
It probably has to do with the time of the completion date.
In redmine, the completion date is managed by datetime
It's possible that the timezone correction is wrong.
I'll look into it over the weekend.

Could you tell me what kind of database and timezone of your redmine.

**Comment by soladev** [comment]
I'm using MySQL and Redmine is using the timezone Etc/UTC

**Comment by soladev** [comment]
I've read the code and I think I've found out where this go wrong. I'm not used to Ruby so I may have misread some lines, but from my understanding : an issue "1" can't appears at two points on the charts, meaning that when an progress get overwritten on day D+1, the progress set on day D doesn't appear anymore on the chart. 

Doesn't seems easy to fix though...

**Comment by momibun926** [comment]
Hi, @soladev 
Thanks for the reply.
Yes, it seems that the dates on the chart are not being converted correctly.
I am using a different method to convert the completion date (datetime) from the database to the date on the chart.

　Database completion date: in_time_zone
　Date on chart: to_time(:local)

Maybe the cause is this difference.
I just pushed the fix code to branch: master, could you please try it?

**Comment by momibun926** [comment]
Hi, @soladev 
I may have made a slight mistake.
Once an issue is completed, the progress rate during the process cannot be displayed in the chart.
The chart (history) does not reflect the percentage of progress, because it considers the EV of the status date to be important.

It is expected that it will be quite a difficult implementation to reflect the past progress rate of a completed ISSUE in the chart.

**Comment by soladev** [comment]
Okay thanks you for letting me know, I figured it would be a complex implementation. 

From what I can tell, the code on master is working as expected.

**Comment by momibun926** [comment]
Hi, @soladev 
I tried to implement it, and pushed it to Branch: 5.3_develop.
If you are interested in it, please try to use it.
However, the code is not very good　:(

**Comment by soladev** [comment]
From what I can tell it's working as expected on branch 5.3_develop, thanks a lot !
